// geo-fixturegen regenerates fixtures/nmea_replay.txt: REAL-format AIVDM
// sentences produced by the go-ais encoder (valid checksums, bit layout and
// fragmentation) for documented SYNTHETIC vessels. The fixtures are
// synthetic-format-valid development data with provenance documented in
// README.md — they are never live traffic and GEO_REPLAY_FILE refuses to
// run when APP_ENV=prod.
package main

import (
	"fmt"
	"os"

	ais "github.com/BertoldVdb/go-ais"
	"github.com/BertoldVdb/go-ais/aisnmea"
	nmea "github.com/adrianmo/go-nmea"
)

// syntheticVessel is a documented fixture vessel (name prefix SYNTH marks it
// as synthetic everywhere it surfaces).
type syntheticVessel struct {
	mmsi uint32
	name string
}

var syntheticVessels = []syntheticVessel{
	{657210300, "SYNTH TRADER ONE"}, // Nigerian-flag (MID 657) cargo sample
	{657221000, "SYNTH FERRY TWO"},  // Nigerian-flag class B ferry sample
	{235081000, "SYNTH COASTER"},    // foreign-flag (MID 235) coaster sample
}

func main() {
	codec := aisnmea.NMEACodecNew(ais.CodecNew(false, false))
	out, err := os.Create("fixtures/nmea_replay.txt")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer out.Close()
	fmt.Fprintln(out, "# Synthetic AIS replay fixture for blueeconomy-geo-service.")
	fmt.Fprintln(out, "# REAL-format AIVDM generated by the go-ais encoder (geo-fixturegen);")
	fmt.Fprintln(out, "# vessels are synthetic (SYNTH name prefix), never live traffic.")
	emit := func(packet ais.Packet, tag nmea.TagBlock) {
		for _, sentence := range codec.EncodeSentence(aisnmea.VdmPacket{
			Packet:      packet,
			TalkerID:    "AI",
			MessageType: "VDM",
			TagBlock:    tag,
		}) {
			fmt.Fprintln(out, sentence)
		}
	}
	tag := func(source string, unix int64) nmea.TagBlock {
		return nmea.TagBlock{Source: source, Time: unix}
	}
	base := int64(1782918800) // fixture clock
	// SYNTH TRADER ONE: static data then a short track crossing the Apapa
	// sample zone used by the integration tests.
	emit(ais.ShipStaticData{
		Header:               ais.Header{MessageID: 5, UserID: 657210300},
		Valid:                true,
		ImoNumber:            9074729,
		CallSign:             "5NAB2",
		Name:                 "SYNTH TRADER ONE",
		Type:                 70,
		Dimension:            ais.FieldDimension{A: 120, B: 20, C: 8, D: 12},
		FixType:              1,
		MaximumStaticDraught: 8.5,
		Destination:          "APAPA",
	}, tag("ais-rx-apapa-02", base))
	track := [][2]float64{
		{6.4000, 3.3500}, {6.4050, 3.3600}, {6.4100, 3.3700}, {6.4180, 3.3725}, {6.4250, 3.3800},
	}
	for i, point := range track {
		emit(ais.PositionReport{
			Header:             ais.Header{MessageID: 1, UserID: 657210300},
			Valid:              true,
			NavigationalStatus: 0,
			Sog:                8.4,
			PositionAccuracy:   true,
			Longitude:          ais.FieldLatLonFine(point[1]),
			Latitude:           ais.FieldLatLonFine(point[0]),
			Cog:                127.5,
			TrueHeading:        126,
		}, tag("ais-rx-apapa-02", base+int64(60*i)))
	}
	// SYNTH FERRY TWO: class B position.
	emit(ais.StandardClassBPositionReport{
		Header:    ais.Header{MessageID: 18, UserID: 657221000},
		Valid:     true,
		Sog:       5.2,
		Longitude: 3.3950,
		Latitude:  6.4500,
		Cog:       90.0,
	}, tag("ais-rx-lagos-01", base+300))
	// SYNTH COASTER: extended class B (position + static in one type 19).
	emit(ais.ExtendedClassBPositionReport{
		Header:    ais.Header{MessageID: 19, UserID: 235081000},
		Valid:     true,
		Sog:       6.1,
		Longitude: 3.3000,
		Latitude:  6.3000,
		Cog:       45.0,
		Name:      "SYNTH COASTER",
		Type:      37,
		Dimension: ais.FieldDimension{A: 60, B: 12, C: 5, D: 5},
		FixType:   1,
	}, tag("ais-rx-bonny-01", base+360))
	fmt.Println("fixtures/nmea_replay.txt regenerated (synthetic fixture vessels)")
}
